language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "0.12.4"
  - "0.12.7"
  - "4.0.0"
  - "4.1.0"
  - "4.1.1"
  - "4.2.1"
  - "4.2.2"
  - "5.0.0"
